name: DescentIntoDarkness
main: com.gmail.sharpcastle33.did.DescentIntoDarkness
version: ${project.version}
api-version: 1.13
depend:
   - ProtocolLib
   - FastAsyncWorldEdit
   - Multiverse-Core
   - MythicMobs
softdepend:
   - NobilityItems
   - HiddenOre
commands:
   did:
      description: Descent Into Darkness main command
      usage: /did <argument> [other stuff]
      aliases: [ descent ]
permissions:
   did.command:
      description: Allows the user to use the main command
      default: op
